# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NBDEVTutorial',
                'doc_host': 'https://Nbglut.github.io',
                'git_url': 'https://github.com/Nbglut/NBDEVTutorial',
                'lib_path': 'NBDEVTutorial'},
  'syms': {'NBDEVTutorial.core': {'NBDEVTutorial.core.foo': ('core.html#foo', 'NBDEVTutorial/core.py')}}}